version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.prod
    env_file:
      - ./env/.env.prod
    environment:
      NODE_ENV: production
    restart: always
    ports:
      - 3000:3000
