FROM node:20-slim

WORKDIR /app

COPY package*.json ./
# https://esbuild.github.io/getting-started/#simultaneous-platforms
RUN npm i --no-audit --no-fund

COPY . .

COPY docker-entrypoint.sh ./docker-entrypoint.sh
COPY scripts/wait-for-it.sh ./scripts/wait-for-it.sh

# https://stackoverflow.com/a/56791772/26860113
RUN sed -i 's/\r$//' ./docker-entrypoint.sh ./scripts/wait-for-it.sh

# Disable nextjs telemetary
ENV NEXT_TELEMETRY_DISABLED 1

ENTRYPOINT ["sh", "./docker-entrypoint.sh"]
