FROM node:20-slim

WORKDIR /app
# https://esbuild.github.io/getting-started/#simultaneous-platforms
COPY package.json ./

RUN npm i --verbose

COPY . .

# Disable nextjs telemetary
ENV NEXT_TELEMETRY_DISABLED 1

CMD ["npm", "run", "dev"]
