FROM node:20-slim

WORKDIR /app

COPY package*.json ./
# https://esbuild.github.io/getting-started/#simultaneous-platforms
RUN npm i --verbose

COPY . .
COPY docker-entrypoint.sh ./

# Disable nextjs telemetary
ENV NEXT_TELEMETRY_DISABLED 1

ENTRYPOINT ["sh", "./docker-entrypoint.sh"]
